# Generated by Django 6.0.3 on 2026-03-11 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontoDeColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('materiais_aceitos', models.ManyToManyField(blank=True, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='solicitacoes/')),
                ('tipo_solicitacao', models.CharField(choices=[('nao_especificado', 'Não Especificado'), ('denuncia', 'Denúncia'), ('agendamento', 'Agendamento')], default='nao_especificado', max_length=20)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='enviada', max_length=20)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('volume_estimado', models.CharField(max_length=100)),
                ('materiais', models.ManyToManyField(blank=True, to='core.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='core.solicitacao')),
            ],
        ),
    ]
